import { Body, EclipticLongitude } from "astronomy-engine";
const signs=["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"];
const bodies=[["Sun",Body.Sun],["Moon",Body.Moon],["Mercury",Body.Mercury],["Venus",Body.Venus],["Mars",Body.Mars],["Jupiter",Body.Jupiter],["Saturn",Body.Saturn]];
const places={"new delhi":[28.6139,77.209],"delhi":[28.6139,77.209],"mumbai":[19.076,72.8777],"kolkata":[22.5726,88.3639],"chennai":[13.0827,80.2707],"bengaluru":[12.9716,77.5946],"bangalore":[12.9716,77.5946],"bhubaneswar":[20.2961,85.8245],"ranchi":[23.3441,85.3096],"patna":[25.5941,85.1376],"hyderabad":[17.385,78.4867],"pune":[18.5204,73.8567]};
function coords(location){const k=String(location||"").toLowerCase().trim();for(const n of Object.keys(places))if(k.includes(n))return {lat:places[n][0],lon:places[n][1],verified:true};return {lat:20.5937,lon:78.9629,verified:false}}
function jd(date){return date.getTime()/86400000+2440587.5}
function gmst(date){const d=jd(date)-2451545;return ((280.46061837+360.98564736629*d)%360+360)%360}
function pos(name,body,date){const longitude=((EclipticLongitude(body,date)%360)+360)%360;return {name,longitude:+longitude.toFixed(2),sign:signs[Math.floor(longitude/30)],degree:+(longitude%30).toFixed(2)}}
function insight(topic,p){const get=n=>p.find(x=>x.name===n);if(topic.startsWith("Career"))return `Career reflection uses Sun in ${get("Sun").sign}, Mercury in ${get("Mercury").sign}, Mars in ${get("Mars").sign}, Jupiter in ${get("Jupiter").sign} and Saturn in ${get("Saturn").sign}. Focus on practical skill-building and consistency rather than treating this as a prediction.`;if(topic.startsWith("Love"))return `Relationship reflection uses Venus in ${get("Venus").sign}, Moon in ${get("Moon").sign} and Mars in ${get("Mars").sign}. Use these as traditional symbolic themes alongside real communication and choices.`;return `Personal-growth reflection uses Sun in ${get("Sun").sign}, Moon in ${get("Moon").sign}, Mercury in ${get("Mercury").sign} and Mars in ${get("Mars").sign}.`}
export default async function handler(req,res){res.setHeader("Access-Control-Allow-Origin","*");if(req.method==="OPTIONS")return res.status(204).end();if(req.method!=="POST")return res.status(405).json({error:"Use POST"});try{const b=req.body||{};const name=String(b.name||"").trim(),dob=String(b.dob||""),time=String(b.time||""),location=String(b.location||"").trim(),topic=String(b.topic||"Personal growth");if(!name||!dob||!time||!location)return res.status(400).json({error:"Please enter name, date of birth, birth time and birthplace."});const [y,m,d]=dob.split("-").map(Number),[hh,mm]=time.split(":").map(Number);if(!Number.isFinite(y)||!Number.isFinite(m)||!Number.isFinite(d)||!Number.isFinite(hh)||!Number.isFinite(mm)||hh<0||hh>23||mm<0||mm>59)return res.status(400).json({error:"Invalid birth date or time."});const date=new Date(Date.UTC(y,m-1,d,hh-5,mm-30));if(Number.isNaN(date.getTime()))return res.status(400).json({error:"Invalid birth details."});const c=coords(location),asc=gmst(date)+c.lon;const ascNorm=((asc%360)+360)%360;const planets=bodies.map(([n,b])=>{const x=pos(n,b,date);return {...x,house:Math.floor((((x.longitude-ascNorm)+360)%360)/30)+1}});return res.status(200).json({ok:true,chart:{birthDate:dob,birthTime:time,birthPlace:location,coordinates:c,ascendant:{sign:signs[Math.floor(ascNorm/30)],degree:+(ascNorm%30).toFixed(2)},planets},reading:`${name}, your calculated chart uses the entered date and time. Ascendant: ${signs[Math.floor(ascNorm/30)]}. `+insight(topic,planets),disclaimer:"Traditional astrology is interpretive and not scientifically validated. Unsupported birthplaces use approximate coordinates."});}catch(e){console.error("reading error",e?.stack||e);return res.status(500).json({error:"Server error while calculating the reading."})}}